name: "Build & Abb"

on:
  workflow_dispatch:
    branches: main

jobs:
  build:
    name: aab file
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup-Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.4'
          channel: 'stable'

      - name: Clone Repository
        run: git clone https://${{secrets.SECRET_KEY}}@github.com/punisher-303/ECHOPULS.git

      - name: Install Dependencies
        run: cd ECHOPULS && flutter pub get

      - name: Extract version from pubspec.yaml
        shell: powershell
        run: |
          $vLine = Select-String -Path ECHOPULS\pubspec.yaml -Pattern '^version:\s*(\S+)' | Select-Object -First 1
          if (-not $vLine) { Write-Error 'version not found in pubspec.yaml'; exit 1 }
          $ver = $vLine.Matches[0].Groups[1].Value.Split('+')[0]
          echo "VERSION=$ver" >> $env:GITHUB_ENV

      - name: Set build number
        shell: pwsh
        run: |
          $buildNumber = 2096
          Write-Host "Setting BUILDVERSION to: $buildNumber"
          "BUILDVERSION=$buildNumber" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Create keystore file
        run: |
          $b64 = "${{ secrets.KEY_STORE }}"
          $filename = "./ECHOPULS/android/Echopulse.jks"
          $bytes = [Convert]::FromBase64String($b64)
          [IO.File]::WriteAllBytes($filename, $bytes)     

      - name: Create Keystore properties
        run: |
          echo keyPassword=\${{ secrets.KEY_PASSWORD }} > ./ECHOPULS/android/key.properties
          echo storePassword=\${{ secrets.STORE_PASSWORD }} >> ./ECHOPULS/android/key.properties
          echo keyAlias=\${{ secrets.KEY_ALIAS }} >> ./ECHOPULS/android/key.properties

      - name: Build Android App Bundle
        shell: pwsh
        run: |
          Write-Host "Building AAB with build number: $env:BUILDVERSION"
          cd ECHOPULS
          flutter build appbundle --release --build-number $env:BUILDVERSION

      - name: Rename Android App Bundle
        run: |
          Rename-Item -Path "ECHOPULS/build/app/outputs/bundle/release/*.aab" -NewName "echo_pulse_android_v${{ env.VERSION }}+${{ env.BUILDVERSION }}.aab"

      - name: Upload Artifacts (Windows+Android)
        uses: actions/upload-artifact@v4
        with:
          name: Release
          path: |
            ECHOPULS/build/app/outputs/bundle/release/echo_pulse_android_v${{ env.VERSION }}+${{ env.BUILDVERSION }}.aab

      - name: Create Release (Windows+Android)
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ECHOPULS/build/app/outputs/bundle/release/echo_pulse_android_v${{ env.VERSION }}+${{ env.BUILDVERSION }}.aab
          tag: v${{ env.VERSION }}+${{ env.BUILDVERSION }}
          token: ${{secrets.SECRET_KEY}}
          allowUpdates: true
          omitBody: true
          prerelease: false