name: "Build & Check"


on:
  workflow_dispatch:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'CODE_OF_CONDUCT.md'
      - './fastlane/**'
      - './ghpage/**'
    branches: main
    
jobs:
    build:
        name: Build & Check
        runs-on: windows-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup-Java
              uses: actions/setup-java@v3.12.0
              with:
                distribution: 'oracle'
                java-version: '17'

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.35.4'
                channel: 'stable'

            - name: Clone Repository
              run: git clone https://${{secrets.SECRET_KEY}}@github.com/punisher-303/ECHOPULS.git
            
            - name: Install Dependencies
              run: cd ECHOPULS && flutter pub get
            
            - name: Extract version from pubspec.yaml
              shell: powershell
              run: |
                  $vLine = Select-String -Path pubspec.yaml -Pattern '^version:\s*(\S+)' | Select-Object -First 1
                  if (-not $vLine) { Write-Error 'version not found in pubspec.yaml'; exit 1 }
                  $ver = $vLine.Matches[0].Groups[1].Value.Split('+')[0]
                  echo "VERSION=$ver" >> $env:GITHUB_ENV

            
            - name: Build App files
              run: cd ECHOPULS && flutter build apk --release --build-number ${{github.run_number}}


            - name: Rename APK file
              run: Rename-Item -Path "ECHOPULS/build/app/outputs/flutter-apk/app-release.apk" -NewName "echo_pulse_android_v$env:VERSION+${{github.run_number}}.apk"

            - name: Build Windows App
              run: flutter build windows --release --build-number ${{github.run_number}}

            - name: Rename file
              run: Rename-Item -Path "ECHOPULS/build/windows/x64/runner/Release/bloomee.exe" -NewName "Bloomee.exe"
           
            - name: ZIP build
              run: Compress-Archive -Path ECHOPULS/build/windows/x64/runner/Release/* -Destination  ECHOPULS/build/windows/x64/echo_pulse_windows_x64_v$env:VERSION+${{github.run_number}}.zip
            
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: Release
                path: |
                  ECHOPULS/build/app/outputs/flutter-apk/echo_pulse_android_v$env:VERSION+${{github.run_number}}.apk
                  ECHOPULS/build/windows/x64/echo_pulse_windows_x64_v$env:VERSION+${{github.run_number}}.zip


    