name: "Build & Check"


on:
  workflow_dispatch:
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'CODE_OF_CONDUCT.md'
      - './fastlane/**'
    branches: main
    
jobs:
    build:
        name: Build & Check
        runs-on: windows-latest
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - name: Setup-Java
              uses: actions/setup-java@v3.12.0
              with:
                distribution: 'oracle'
                java-version: '17'

            - name: Setup Flutter
              uses: subosito/flutter-action@v2
              with:
                flutter-version: '3.27.4'
                channel: 'stable'

            - name: Clone Repository
              run: git clone https://${{secrets.SECRET_KEY}}@github.com/punisher-303/ECHOPULS.git
            
            - name: Install Dependencies
              run: cd ECHOPULS && flutter pub get
            
            - name: Create .env file
              run: echo "CLIENT_ID = XXXXX\nCLIENT_SECRET = XXXX EOF" > ECHOPULS/assets/.env

            
            - name: Build App files
              run: cd ECHOPULS && flutter build apk --release --build-number ${{github.run_number}}


            - name: Rename APK file
              run: Rename-Item -Path "ECHOPULS/build/app/outputs/flutter-apk/app-release.apk" -NewName "echo_pulse_android_v4.5.2+${{github.run_number}}.apk"

            - name: Build Windows App
              run: flutter build windows --release --build-number ${{github.run_number}}

            - name: Rename file
              run: Rename-Item -Path "ECHOPULS/build/windows/x64/runner/Release/bloomee.exe" -NewName "Bloomee.exe"
           
            - name: ZIP build
              run: Compress-Archive -Path ECHOPULS/build/windows/x64/runner/Release/* -Destination  ECHOPULS/build/windows/x64/echo_pulse_windows_x64_v4.5.2+${{github.run_number}}.zip
            
            - name: Upload Artifacts
              uses: actions/upload-artifact@v4
              with:
                name: Release
                path: |
                  ECHOPULS/build/app/outputs/flutter-apk/echo_pulse_android_v4.5.2+${{github.run_number}}.apk
                  ECHOPULS/build/windows/x64/echo_pulse_windows_x64_v4.5.2+${{github.run_number}}.zip


    