name: "Build for Linux"

on:
  workflow_dispatch:
    branches: main


jobs:
  linux_build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          channel: stable
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
          sudo apt-get install -y ninja-build libgtk-3-dev cmake git libmpv-dev clang

      - name: Clone Repository
        run: git clone https://${{secrets.SECRET_KEY}}@github.com/punisher-303/ECHOPULS.git
              
      - name: Install Dependencies
        run: cd ECHOPULS && flutter pub get
            
      - name: Create .env file
        run: echo "CLIENT_ID = XXXXX\nCLIENT_SECRET = XXXX EOF" > ECHOPULS/assets/.env

      - name: Build Linux App
        run: cd ECHOPULS && flutter build linux --release --build-number ${{github.run_number}}

      - name: Zip Linux App
        run: |
          cd ECHOPULS/build/linux/x64/release/bundle
          zip -r echo_pulse_linux_v4.5.5_dev+${{github.run_number}}.zip .
        


      - name: Upload Artifacts Linux App
        uses: actions/upload-artifact@v4
        with:
          name: echo_pulse_linux_dev
          path: ECHOPULS/build/linux/x64/release/bundle/echo_pulse_linux_v4.5.5_dev+${{github.run_number}}.zip
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ECHOPULS/build/linux/x64/release/bundle/echo_pulse_linux_v4.5.5_dev+${{github.run_number}}.zip
          tag: v4.5.5+78
          token: ${{secrets.SECRET_KEY}}
          allowUpdates: true
          omitBody: true
          prerelease: true
