name: "Build for Linux"

on:
  workflow_dispatch:
    branches: main


jobs:
  linux_build:
    name: Linux Build
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.27.4'
          channel: stable
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y curl git unzip xz-utils zip libglu1-mesa
          sudo apt-get install -y ninja-build libgtk-3-dev cmake git libmpv-dev clang

      - name: Clone Repository
        run: git clone https://${{secrets.SECRET_KEY}}@github.com/punisher-303/ECHOPULS.git

      - name: Install Dependencies
        run: cd ECHOPULS && flutter pub get

      - name: Extract version from pubspec.yaml
        run: |
          ver=$(grep -m1 -E '^version:\s*' ECHOPULS/pubspec.yaml | awk '{print $2}' | cut -d'+' -f1)
          if [ -z "$ver" ]; then echo "version not found in pubspec.yaml"; exit 1; fi
          echo "VERSION=$ver" >> $GITHUB_ENV

      - name: Create .env file
        run: echo "CLIENT_ID = XXXXX\nCLIENT_SECRET = XXXX EOF" > ECHOPULS/assets/.env

      - name: Build Linux App
        run: |
          adjusted=$(( ${{ github.run_number }} + 121 ))
          echo "ADJUSTED_RUN_NUMBER=$adjusted" >> $GITHUB_ENV
          cd ECHOPULS && flutter build linux --release --build-number $adjusted

      - name: Zip Linux App
        run: |
          cd ECHOPULS/build/linux/x64/release/bundle
          zip -r echo_pulse_linux_v${{ env.VERSION }}+${{ env.ADJUSTED_RUN_NUMBER }}.zip .

      - name: Upload Artifacts Linux App
        uses: actions/upload-artifact@v4
        with:
          name: echo_pulse_linux
          path: ECHOPULS/build/linux/x64/release/bundle/echo_pulse_linux_v${{ env.VERSION }}+${{ env.ADJUSTED_RUN_NUMBER }}.zip
      
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            ECHOPULS/build/linux/x64/release/bundle/echo_pulse_linux_v${{ env.VERSION }}+${{ env.ADJUSTED_RUN_NUMBER }}.zip
          tag: v${{ env.VERSION }}+${{github.run_number}}
          token: ${{secrets.SECRET_KEY}}
          allowUpdates: true
          omitBody: true
          prerelease: true    
